name: BingoGCN
channels:
  - dglteam
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - aom=3.5.0
  - attr=2.5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.105
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.105
  - cuda-nsight-compute=12.1.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.105
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.105
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.105
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.105
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-version=11.6
  - cuda-visual-tools=11.6.1
  - cudatoolkit=11.6.0
  - cudnn=8.8.0.121
  - cupy=12.0.0
  - cython
  - dav1d=1.2.1
  - dbus=1.13.18
  - dgl-cuda11.6=0.9.1post1
  - expat=2.5.0
  - fastrlock=0.8
  - ffmpeg=5.1.2
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - gds-tools=1.6.1.9
  - gettext=0.21.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.14
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=7.3.0
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - jasper=4.0.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libaec=1.0.6
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=16.0.5
  - libclang13=16.0.5
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.6.1.9
  - libcufile-dev=1.6.1.9
  - libcups=2.3.3
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurl=8.1.2
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.18
  - libdrm=2.4.114
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.2
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libglu=9.0.0
  - libgpg-error=1.46
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.5
  - libmagma=2.7.1
  - libmagma_sparse=2.7.1
  - libnghttp2=1.52.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnsl=2.0.0
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libogg=1.3.5
  - libopenblas=0.3.23
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.0
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.13.0
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.5
  - llvmlite=0.40.0
  - lz4-c=1.9.4
  - magma=2.7.1
  - markupsafe=2.1.1
  - mkl=2022.2.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.31.3
  - mpmath=1.2.1
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nccl=2.17.1.1
  - ncurses=6.4
  - nettle=3.8.1
  - ninja=1.11.1
  - nsight-compute=2023.1.1.4
  - nspr=4.35
  - nss=3.89.1
  - numba=0.57.0
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - p11-kit=0.24.1
  - pcre2=10.40
  - pillow=9.5.0
  - pip
  - pixman=0.40.0
  - pkg-config=0.29.2
  - psutil=5.9.5
  - pulseaudio-client=16.1
  - py-opencv=4.7.0
  - pycparser=2.21
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - python_abi=3.9
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.2.2
  - setuptools=67.8.0
  - sleef=3.5.1
  - sqlite=3.41.2
  - svt-av1=1.4.1
  - sympy=1.11.1
  - tbb=2021.9.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tqdm=4.65.0
  - typing_extensions=4.5.0
  - wheel=0.38.4
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
